export const extensions: IconMap = {
  angular: ['ng-template'],
  apple: ['applescript', 'ipa'],
  arduino: ['ino'],
  astro: ['astro'],
  bash: ['bash', 'sh', 'awk'],
  bat: ['bat'],
  c: ['c', 'i', 'mi'],
  css: ['css'],
  css_map: ['css.map'],
  certificate: ['cer', 'cert', 'crt', 'pfx'],
  clojure: ['clj', 'cljs', 'cljc'],
  coffeescript: ['coffee', 'cson', 'iced'],
  cpp: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
  csharp: ['cs', 'csx'],
  csv: ['csv', 'tsv', 'psv'],
  cucumber: ['feature', 'features'],
  cuda: ['cu', 'cuh'],
  dart: ['dart'],
  dart_generated: ['freezed.dart', 'g.dart'],
  database: [
    'pdb',
    'sql',
    'pks',
    'pkb',
    'accdb',
    'mdb',
    'sqlite',
    'sqlite3',
    'pgsql',
    'postgres',
    'psql',
    'db',
    'db3',
  ],
  django: ['djt'],
  doc: ['doc', 'docx', 'rtf', 'odt'],
  docker: ['dockerfile'],
  docker_ignore: ['dockerignore'],
  elixir: ['ex', 'exs', 'eex', 'leex', 'heex'],
  elm: ['elm'],
  erlang: ['erl'],
  fsharp: ['fs', 'fsx', 'fsi', 'fsproj'],
  go: ['go'],
  gradle: ['gradle'],
  graphql: ['graphql', 'gql'],
  groovy: ['groovy'],
  h: ['h'],
  handlebars: ['hbs', 'mustache'],
  haskell: ['hs'],
  hpp: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
  html: ['htm', 'xhtml', 'html_vm', 'asp'],
  image: [
    'png',
    'jpeg',
    'jpg',
    'gif',
    'ico',
    'tif',
    'tiff',
    'psd',
    'psb',
    'ami',
    'apx',
    'avif',
    'bmp',
    'bpg',
    'brk',
    'cur',
    'dds',
    'dng',
    'exr',
    'fpx',
    'gbr',
    'img',
    'jbig2',
    'jb2',
    'jng',
    'jxr',
    'pgf',
    'pic',
    'raw',
    'webp',
    'eps',
    'afphoto',
    'ase',
    'aseprite',
    'clip',
    'cpt',
    'heif',
    'heic',
    'kra',
    'mdp',
    'ora',
    'pdn',
    'reb',
    'sai',
    'tga',
    'xcf',
    'jfif',
    'ppm',
    'pbm',
    'pgm',
    'pnm',
  ],
  java: ['java', 'jsp'],
  java_class: ['class'],
  java_jar: ['jar'],
  javascript: ['js', 'cjs', 'esx', 'mjs'],
  javascript_config: ['jsconfig.json'],
  javascript_map: ['js.map', 'mjs.map', 'cjs.map'],
  javascript_react: ['jsx'],
  javascript_test: [
    'spec.js',
    'spec.cjs',
    'spec.mjs',
    'e2e-spec.js',
    'e2e-spec.cjs',
    'e2e-spec.mjs',
    'test.js',
    'test.cjs',
    'test.mjs',
    'js.snap',
    'cy.js',
    'spec.jsx',
    'test.jsx',
    'jsx.snap',
    'cy.jsx',
  ],
  json: [
    'json',
    'jsonc',
    'tsbuildinfo',
    'json5',
    'jsonl',
    'ndjson',
  ],
  julia: ['jl'],
  jupyter: ['ipynb'],
  key: ['pub', 'key', 'pem', 'asc', 'gpg', 'passwd'],
  kotlin: ['kt', 'kts'],
  laravel: ['blade.php', 'inky.php'],
  latex: ['tex', 'sty', 'dtx', 'ltx'],
  lib: ['lib', 'bib', 'dll', 'dlc'],
  lisp: ['lisp', 'lsp', 'cl', 'fast'],
  log: ['log'],
  lua: ['lua'],
  makefile: ['mk'],
  markdown: ['md', 'markdown', 'rst'],
  markdown_mdx: ['mdx'],
  marko: ['marko'],
  nextflow: ['nf'],
  nginx: ['nginx', 'nginxconfig'],
  nix: ['nix'],
  pdf: ['pdf'],
  perl: ['pm', 'raku'],
  php: ['php'],
  powershell: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
  prisma: ['prisma'],
  properties: [
    'ini',
    'dlc',
    'config',
    'conf',
    'properties',
    'prop',
    'settings',
    'option',
    'props',
    'prefs',
    'sln.dotsettings',
    'sln.dotsettings.user',
    'cfg',
  ],
  python: ['py'],
  python_compiled: ['pyc', 'pyo', 'pyd'],
  r: ['r', 'rmd'],
  razor: ['cshtml', 'vbhtml'],
  reason: ['re', 'rei'],
  rescript: ['res', 'resi'],
  ruby: ['rb', 'erb'],
  rust: ['rs', 'ron'],
  sass: ['scss', 'sass'],
  scala: ['scala', 'sc'],
  search: ['code-search'],
  shader: [
    'glsl',
    'vert',
    'tesc',
    'tese',
    'geom',
    'frag',
    'comp',
    'vert.glsl',
    'tesc.glsl',
    'tese.glsl',
    'geom.glsl',
    'frag.glsl',
    'comp.glsl',
    'vertex.glsl',
    'geometry.glsl',
    'fragment.glsl',
    'compute.glsl',
    'ts.glsl',
    'gs.glsl',
    'vs.glsl',
    'fs.glsl',
    'shader',
    'vertexshader',
    'fragmentshader',
    'geometryshader',
    'computeshader',
    'hlsl',
    'pixel.hlsl',
    'geometry.hlsl',
    'compute.hlsl',
    'tessellation.hlsl',
    'px.hlsl',
    'geom.hlsl',
    'comp.hlsl',
    'tess.hlsl',
    'wgsl',
  ],
  slide: [
    'pptx',
    'ppt',
    'pptm',
    'potx',
    'potm',
    'ppsx',
    'ppsm',
    'pps',
    'ppam',
    'ppa',
    'odp',
  ],
  spreadsheet: ['xlsx', 'xlsm', 'xls', 'ods'],
  storybook: ['story.js', 'story.ts', 'stories.js', 'stories.ts'],
  storybook_svelte: ['story.svelte', 'stories.svelte'],
  storybook_vue: ['story.vue', 'stories.vue'],
  svelte: ['svelte'],
  svg: ['svg'],
  swift: ['swift'],
  tauri: ['tauri'],
  terraform: ['tf', 'tf.json', 'tfvars', 'tfstate'],
  toml: ['toml'],
  txt: ['txt'],
  typescript: ['ts'],
  typescript_config: ['tsconfig.json'],
  typescript_def: ['d.ts', 'd.cts', 'd.mts'],
  typescript_react: ['tsx'],
  typescript_test: [
    'spec.ts',
    'spec.cts',
    'spec.mts',
    'cy.ts',
    'e2e-spec.ts',
    'e2e-spec.cts',
    'e2e-spec.mts',
    'test.ts',
    'test.cts',
    'test.mts',
    'ts.snap',
    'spec.tsx',
    'test.tsx',
    'tsx.snap',
    'cy.tsx',
  ],
  unity: ['unity'],
  v: ['v'],
  visual_studio: [
    'csproj',
    'ruleset',
    'sln',
    'suo',
    'vb',
    'vbs',
    'vcxitems',
    'vcxitems.filters',
    'vcxproj',
    'vcxproj.filters',
  ],
  vs_code: [
    'vsixmanifest',
    'vsix',
    'code-workplace',
    'code-workspace',
    'code-profile',
    'code-snippets',
  ],
  vs_code_ignore: ['vscodeignore'],
  web_assembly: ['wat', 'wasm'],
  workflow: ['workflows/yml', 'workflows/yaml'],
  xml: [
    'xml',
    'plist',
    'xsd',
    'dtd',
    'xsl',
    'xslt',
    'resx',
    'iml',
    'xquery',
    'tmLanguage',
    'manifest',
    'project',
    'xml.dist',
    'xml.dist.sample',
    'dmn',
    'jrxml',
  ],
  yaml: ['yml', 'yaml'],
  zig: ['zig'],
}
