export const extensions: IconMap = {
  _3d: [
    'ac',
    'blend',
    'dxf',
    'fbx',
    'mesh',
    'mqo',
    'mtl',
    'obj',
    'pmd',
    'pmx',
    'reality',
    'skp',
    'stl',
    'stp',
    'usdz',
    'vac',
    'vdp',
    'vox',
  ],
  advpl: ['prw', 'prx', 'ptm', 'tlpp', 'ch'],
  android: ['apk', 'smali', 'dex'],
  angular: ['ng-template'],
  antlr: ['g4'],
  api_blueprint: ['apib', 'apiblueprint'],
  apl: ['apl'],
  apple: ['applescript', 'ipa'],
  apps_script: ['gs'],
  arduino: ['ino'],
  ascii_doctor: ['ad', 'adoc', 'asciidoc'],
  assembly: [
    'asm',
    'a51',
    'inc',
    'nasm',
    's',
    'ms',
    'agc',
    'ags',
    'aea',
    'argus',
    'mitigus',
    'binsource',
  ],
  astro: ['astro'],
  audio: ['mp3', 'wma', 'wav', 'm4a', 'flac', 'aiff'],
  autohotkey: ['ahk'],
  autoit: ['au3', 'a3x'],
  azure: ['azcli'],
  ballerina: ['bal', 'balx'],
  bash: ['bash', 'sh', 'awk'],
  bat: ['bat'],
  bazel: ['bzl', 'bazel'],
  bicep: ['bicep'],
  binary: ['bin'],
  c: ['c', 'i', 'mi'],
  cabal: ['cabal'],
  cadence: ['cdc'],
  cobol: ['cob', 'cbl'],
  coconut: ['coco'],
  command: ['command'],
  css: ['css'],
  css_map: ['css.map'],
  certificate: ['cer', 'cert', 'crt', 'pfx'],
  clojure: ['clj', 'cljs', 'cljc'],
  cmake: ['cmake'],
  cmake_in: ['cmake.in', 'mk.in'],
  coffeescript: ['coffee', 'cson', 'iced'],
  cpp: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
  crystal: ['cr', 'ecr'],
  csharp: ['cs', 'csx', 'csharp'],
  csv: ['csv', 'tsv', 'psv'],
  cucumber: ['feature', 'features'],
  cuda: ['cu', 'cuh'],
  d: ['d'],
  dart: ['dart'],
  database: [
    'pdb',
    'sql',
    'pks',
    'pkb',
    'accdb',
    'mdb',
    'sqlite',
    'sqlite3',
    'pgsql',
    'postgres',
    'psql',
    'db',
    'db3',
  ],
  denizen_script: ['dsc'],
  dhall: ['dhall', 'dhallb'],
  disc: ['iso', 'vcd', 'cue', 'dmg', 'hdd', 'vmdk', 'qcow', 'qcow2', 'qed'],
  django: ['djt'],
  doc: ['doc', 'docx', 'rtf', 'odt', 'pages'],
  docker: ['dockerfile'],
  docker_ignore: ['dockerignore'],
  dotjs: ['def', 'dot', 'jst'],
  drawio: ['drawio', 'dio'],
  ejs: ['ejs'],
  elixir: ['ex', 'exs', 'eex', 'leex', 'heex'],
  elm: ['elm'],
  env: ['env'],
  erlang: ['erl'],
  exe: ['exe', 'msi'],
  figma: ['fig'],
  font: [
    'bmap',
    'eot',
    'fnt',
    'font',
    'fonts',
    'mrf',
    'ntf',
    'odttf',
    'otf',
    'sui',
    'suit',
    'ttc',
    'ttf',
    'woff',
    'woff2',
  ],
  forth: ['4th', 'fth', 'frt'],
  fortran: ['f', 'for', 'f77', 'f90', 'f95', 'f03', 'f08', 'f18', 'f23', 'fypp'],
  foxpro: ['fxp', 'prg'],
  fsharp: ['fs', 'fsx', 'fsi', 'fsproj'],
  gamemaker: ['gml', 'yy', 'yyp', 'yyz'],
  gleam: ['gleam'],
  go: ['go'],
  godot: ['gd'],
  godot_assets: [
    'godot',
    'tres',
    'tscn',
    'gdns',
    'gdnlib',
    'gdshader',
    'gdshaderinc',
    'gdextension',
  ],
  gradle: ['gradle'],
  grain: ['gr'],
  graphql: ['graphql', 'gql'],
  groovy: ['groovy'],
  h: ['h'],
  haml: ['haml'],
  handlebars: ['hbs', 'mustache'],
  haskell: ['hs'],
  haxe: ['hx', 'hxml'],
  hcl: ['hcl'],
  hjson: ['hjson'],
  hpp: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
  html: ['htm', 'xhtml', 'html_vm', 'asp'],
  http: ['http', 'rest', 'cname'],
  i18n: ['pot', 'po', 'mo', 'lang', 'strings'],
  icon: ['ico', 'icns'],
  image: [
    'png',
    'jpeg',
    'jpg',
    'gif',
    'tif',
    'tiff',
    'psd',
    'psb',
    'ami',
    'apx',
    'avif',
    'bmp',
    'bpg',
    'brk',
    'cur',
    'dds',
    'dng',
    'exr',
    'fpx',
    'gbr',
    'img',
    'jbig2',
    'jb2',
    'jng',
    'jxr',
    'pgf',
    'pic',
    'raw',
    'webp',
    'eps',
    'afphoto',
    'ase',
    'aseprite',
    'clip',
    'cpt',
    'heif',
    'heic',
    'kra',
    'mdp',
    'ora',
    'pdn',
    'reb',
    'sai',
    'tga',
    'xcf',
    'jfif',
    'ppm',
    'pbm',
    'pgm',
    'pnm',
  ],
  java: ['java', 'jsp'],
  java_class: ['class'],
  java_jar: ['jar'],
  javascript: ['js', 'cjs', 'esx', 'mjs'],
  javascript_config: ['jsconfig.json'],
  javascript_map: ['js.map', 'mjs.map', 'cjs.map'],
  javascript_react: ['jsx'],
  javascript_test: [
    'spec.js',
    'spec.cjs',
    'spec.mjs',
    'e2e-spec.js',
    'e2e-spec.cjs',
    'e2e-spec.mjs',
    'test.js',
    'test.cjs',
    'test.mjs',
    'js.snap',
    'cy.js',
    'spec.jsx',
    'test.jsx',
    'jsx.snap',
    'cy.jsx',
  ],
  jenkins: ['jenkinsfile', 'jenkins'],
  jinja: ['jinja', 'jinja2', 'j2', 'jinja-html'],
  json: [
    'json',
    'jsonc',
    'tsbuildinfo',
    'json5',
    'jsonl',
    'ndjson',
  ],
  julia: ['jl'],
  jupyter: ['ipynb'],
  key: ['pub', 'key', 'pem', 'asc', 'gpg', 'passwd', 'keystore'],
  kivy: ['kv'],
  kotlin: ['kt', 'kts'],
  laravel: ['blade.php', 'inky.php'],
  latex: ['tex', 'sty', 'dtx', 'ltx'],
  less: ['less'],
  lib: ['lib', 'bib', 'dll', 'dlc'],
  lisp: ['lisp', 'lsp', 'cl', 'fast'],
  livescript: ['ls'],
  log: ['log'],
  lottie: ['lottie'],
  lua: ['lua'],
  mail: ['.ics'],
  makefile: ['mk'],
  markdown: ['md', 'markdown', 'rst'],
  markdown_mdx: ['mdx'],
  marko: ['marko'],
  mathematica: ['nb'],
  matlab: ['mat'],
  mermaid: ['mermaid', 'mmd'],
  meson: ['meson', 'wrap'],
  mint: ['mint'],
  mjml: ['mjml'],
  mojo: ['mojo', '🔥'],
  moonscript: ['moon'],
  nextflow: ['nf'],
  nginx: ['nginx', 'nginxconfig'],
  nim: ['nim'],
  ninja: ['ninja'],
  nix: ['nix'],
  nuget: ['nupkg'],
  nunjucks: ['njk', 'nunjucks'],
  nx: ['nx'],
  ocaml: ['ml', 'mli', 'cmx'],
  odin: ['odin'],
  pawn: ['pwn', 'amx'],
  pdf: ['pdf'],
  perl: ['pm', 'raku'],
  php: ['php'],
  pinejs: ['pine'],
  postcss: ['pcss', 'sss'],
  powershell: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
  prisma: ['prisma'],
  processing: ['pde'],
  prolog: ['p', 'pro', 'pl'],
  properties: [
    'ini',
    'dlc',
    'config',
    'conf',
    'properties',
    'prop',
    'settings',
    'option',
    'props',
    'prefs',
    'sln.dotsettings',
    'sln.dotsettings.user',
    'cfg',
  ],
  proto: ['proto'],
  pug: ['jade', 'pug'],
  puppet: ['pp'],
  purescript: ['purs', 'pure'],
  python: ['py'],
  python_compiled: ['pyc', 'pyo', 'pyd'],
  r: ['r', 'rmd'],
  racket: ['rkt', 'rkts', 'rktd', 'rktl'],
  razor: ['cshtml', 'vbhtml'],
  reason: ['re', 'rei'],
  red: ['red', 'reds'],
  rescript: ['res', 'resi'],
  restql: ['rql', 'restql'],
  riot: ['riot'],
  roblox: ['rbxl', 'rbxlx', 'rbxm', 'rbxmx'],
  ruby: ['rb', 'erb'],
  rust: ['rs', 'ron'],
  sass: ['scss', 'sass'],
  scala: ['scala', 'sc'],
  scheme: ['ss', 'scm'],
  search: ['code-search'],
  shader: [
    'glsl',
    'vert',
    'tesc',
    'tese',
    'geom',
    'frag',
    'comp',
    'vert.glsl',
    'tesc.glsl',
    'tese.glsl',
    'geom.glsl',
    'frag.glsl',
    'comp.glsl',
    'vertex.glsl',
    'geometry.glsl',
    'fragment.glsl',
    'compute.glsl',
    'ts.glsl',
    'gs.glsl',
    'vs.glsl',
    'fs.glsl',
    'shader',
    'vertexshader',
    'fragmentshader',
    'geometryshader',
    'computeshader',
    'hlsl',
    'pixel.hlsl',
    'geometry.hlsl',
    'compute.hlsl',
    'tessellation.hlsl',
    'px.hlsl',
    'geom.hlsl',
    'comp.hlsl',
    'tess.hlsl',
    'wgsl',
  ],
  sketch: ['sketch'],
  slide: [
    'pptx',
    'ppt',
    'pptm',
    'potx',
    'potm',
    'ppsx',
    'ppsm',
    'pps',
    'ppam',
    'ppa',
    'odp',
  ],
  slim: ['slim'],
  smarty: ['tpl'],
  solidity: ['sol'],
  spreadsheet: ['xlsx', 'xlsm', 'xls', 'ods', 'numbers'],
  spwn: ['spwn'],
  stan: ['stan'],
  storybook: [
    'story.js',
    'story.ts',
    'stories.js',
    'stories.ts',
    'story.jsx',
    'stories.jsx',
    'story.tsx',
    'stories.tsx',
  ],
  storybook_svelte: ['story.svelte', 'stories.svelte'],
  storybook_vue: ['story.vue', 'stories.vue'],
  sublime: ['sublime-project', 'sublime-workspace'],
  svelte: ['svelte'],
  svg: ['svg'],
  swift: ['swift'],
  tauri: ['tauri'],
  task: ['taskfile.yml', 'taskfile.yaml'],
  terraform: ['tf', 'tf.json', 'tfvars', 'tfstate', 'tfbackend'],
  tldraw: ['tldr'],
  todo: ['todo'],
  toml: ['toml'],
  tree: ['tree'],
  twig: ['twig'],
  twine: ['tw', 'twee'],
  txt: ['txt'],
  typescript: ['ts'],
  typescript_config: ['tsconfig.json'],
  typescript_def: ['d.ts', 'd.cts', 'd.mts'],
  typescript_react: ['tsx'],
  typescript_test: [
    'spec.ts',
    'spec.cts',
    'spec.mts',
    'cy.ts',
    'e2e-spec.ts',
    'e2e-spec.cts',
    'e2e-spec.mts',
    'test.ts',
    'test.cts',
    'test.mts',
    'ts.snap',
    'spec.tsx',
    'test.tsx',
    'tsx.snap',
    'cy.tsx',
  ],
  uml: ['iuml', 'pu', 'puml', 'plantuml', 'wsd'],
  unity: ['unity'],
  url: ['url'],
  v: ['v'],
  video: [
    'avi',
    'flv',
    'gifv',
    'm2v',
    'm4v',
    'mkv',
    'mov',
    'mp2',
    'mp4',
    'mpe',
    'mpeg',
    'mpg',
    'mpv',
    'ogg',
    'ogv',
    'qt',
    'rm',
    'rmvb',
    'vob',
    'webm',
    'wmv',
    'yuv',
  ],
  velocity: ['vm', 'fhtml', 'vtl'],
  verilog: ['sv', 'svh', 'vhd'],
  vim: ['exrc', 'gvimrc', 'vim', 'vimrc', 'viminfo'],
  visual_studio: [
    'csproj',
    'ruleset',
    'sln',
    'suo',
    'vb',
    'vbs',
    'vcxitems',
    'vcxitems.filters',
    'vcxproj',
    'vcxproj.filters',
    'vcxproj.user',
  ],
  vs_code: [
    'vsixmanifest',
    'vsix',
    'code-workplace',
    'code-workspace',
    'code-profile',
    'code-snippets',
  ],
  vs_code_ignore: ['vscodeignore'],
  web_assembly: ['wat', 'wasm'],
  wolfram: ['wl'],
  workflow: ['workflows/yml', 'workflows/yaml'],
  vagrant: ['vagrantfile'],
  vala: ['vala'],
  xaml: ['xaml'],
  xcode_project: ['pbxproj'],
  xd: ['xd'],
  xib: ['xib', 'nib', 'storyboard'],
  xml: [
    'xml',
    'plist',
    'xsd',
    'dtd',
    'xsl',
    'xslt',
    'resx',
    'iml',
    'xquery',
    'tmLanguage',
    'manifest',
    'project',
    'xml.dist',
    'xml.dist.sample',
    'dmn',
    'jrxml',
  ],
  yaml: ['yml', 'yaml'],
  zig: ['zig'],
  zip: [
    '7z',
    'br',
    'brotli',
    'bz2',
    'bzip2',
    'gz',
    'gzip',
    'lz4',
    'lzma',
    'rar',
    'tar',
    'tgz',
    'txz',
    'tz',
    'xz',
    'zip',
    'zst',
  ],
}
