export const files: IconMap = {
  adonis: ['.adonisrc.json', 'ace'],
  alex: ['.alexrc', '.alexrc.yml', '.alexrc.yaml', 'alexrc.js'],
  angular: ['angular-cli.json', '.angular-cli.json', 'angular.json'],
  apollo: ['apollo.config.js', 'apollo.config.ts'],
  appveyor: ['.appveyor.yml', 'appveyor.yml'],
  astro: [
    'astro.config.js',
    'astro.config.mjs',
    'astro.config.cjs',
    'astro.config.ts',
    'astro.config.cts',
    'astro.config.mts',
  ],
  babel: [
    '.babelrc',
    '.babelrc.cjs',
    '.babelrc.js',
    '.babelrc.mjs',
    '.babelrc.json',
    'babel.config.cjs',
    'babel.config.js',
    'babel.config.mjs',
    'babel.config.json',
    'babel-transform.js',
    '.babel-plugin-macrosrc',
    '.babel-plugin-macrosrc.json',
    '.babel-plugin-macrosrc.yaml',
    '.babel-plugin-macrosrc.yml',
    '.babel-plugin-macrosrc.js',
    'babel-plugin-macros.config.js',
  ],
  bash: ['commit-msg', 'pre-commit', 'pre-push', 'post-merge'],
  browserslist: ['browserslist', '.browserslistrc'],
  capacitor: ['capacitor.config.json', 'capacitor.config.ts'],
  cargo: ['cargo.toml'],
  cargo_lock: ['cargo.lock'],
  changelog: [
    'changelog',
    'changelog.md',
    'changelog.rst',
    'changelog.txt',
    'changes',
    'changes.md',
    'changes.rst',
    'changes.txt',
  ],
  code_of_conduct: [
    'code_of_conduct.md',
    'code_of_conduct.txt',
    'code_of_conduct',
  ],
  code_climate: ['.codeclimate.yml'],
  codecov: ['.codecov.yml', 'codecov.yml'],
  codeowners: ['codeowners'],
  commitlint: [
    '.commitlintrc',
    '.commitlintrc.js',
    '.commitlintrc.cjs',
    '.commitlintrc.ts',
    '.commitlintrc.cts',
    '.commitlintrc.json',
    '.commitlintrc.yaml',
    '.commitlintrc.yml',
    '.commitlint.yaml',
    '.commitlint.yml',
    'commitlint.config.js',
    'commitlint.config.cjs',
    'commitlint.config.ts',
    'commitlint.config.cts',
  ],
  contributing: [
    'contributing',
    'contributing.md',
    'contributing.rst',
    'contributing.txt',
  ],
  cypress: [
    'cypress.json',
    'cypress.env.json',
    'cypress.config.ts',
    'cypress.config.js',
    'cypress.config.cjs',
    'cypress.config.mjs',
  ],
  dart: ['.pubignore'],
  deno: ['deno.json', 'deno.jsonc'],
  deno_lock: ['deno.lock'],
  dependabot: ['dependabot.yml', 'dependabot.yaml'],
  docker: ['dockerfile', 'docker-compose.yml', 'docker-compose.yaml'],
  editorconfig: ['.editorconfig'],
  ember: ['.ember-cli', '.ember-cli.js', 'ember-cli-builds.js'],
  env: [
    '.env.defaults',
    '.env.example',
    '.env.sample',
    '.env.template',
    '.env.schema',
    '.env.local',
    '.env.dev',
    '.env.development',
    '.env.alpha',
    '.env.e2e',
    '.env.qa',
    '.env.dist',
    '.env.prod',
    '.env.production',
    '.env.stage',
    '.env.staging',
    '.env.preview',
    '.env.test',
    '.env.testing',
    '.env.development.local',
    '.env.qa.local',
    '.env.production.local',
    '.env.staging.local',
    '.env.test.local',
    '.env.uat',
    '.env.cypress',
  ],
  eslint: [
    '.eslintrc.js',
    '.eslintrc.cjs',
    '.eslintrc.yaml',
    '.eslintrc.yml',
    '.eslintrc.json',
    '.eslintrc-md.js',
    '.eslintrc-jsdoc.js',
    '.eslintrc',
  ],
  eslint_ignore: ['.eslintignore', '.eslintcache'],
  favicon: ['favicon.ico'],
  firebase: [
    'firebase.json',
    '.firebaserc',
    'firestore.rules',
    'firestore.indexes.json',
  ],
  gatsby: [
    'gatsby-config.js',
    'gatsby-config.mjs',
    'gatsby-config.ts',
    'gatsby-node.js',
    'gatsby-node.mjs',
    'gatsby-node.ts',
    'gatsby-browser.js',
    'gatsby-browser.tsx',
    'gatsby-ssr.js',
    'gatsby-ssr.tsx',
  ],
  git: [
    '.gitignore',
    '.gitconfig',
    '.gitattributes',
    '.gitmodules',
    '.gitkeep',
    '.git-include',
  ],
  gitlab: ['gitlab-ci.yml'],
  gitpod: ['.gitpod.yml'],
  go_mod: ['go.mod', 'go.sum', 'go.work', 'go.work.sum'],
  gradle: ['gradle.properties', 'gradlew', 'gradle-wrapper.properties'],
  graphql: [
    '.graphqlconfig',
    '.graphqlrc',
    '.graphqlrc.json',
    '.graphqlrc.js',
    '.graphqlrc.cjs',
    '.graphqlrc.ts',
    '.graphqlrc.toml',
    '.graphqlrc.yaml',
    '.graphqlrc.yml',
    'graphql.config.json',
    'graphql.config.js',
    'graphql.config.ts',
    'graphql.config.toml',
    'graphql.config.yaml',
    'graphql.config.yml',
  ],
  helm: ['.helmignore'],
  heroku: ['procfile', 'procfile.windows'],
  javascript_config: ['jsconfig.json'],
  jest: [
    'jest.config.js',
    'jest.config.cjs',
    'jest.config.mjs',
    'jest.config.ts',
    'jest.config.cts',
    'jest.config.mts',
    'jest.config.json',
    'jest.e2e.config.js',
    'jest.e2e.config.cjs',
    'jest.e2e.config.mjs',
    'jest.e2e.config.ts',
    'jest.e2e.config.cts',
    'jest.e2e.config.mts',
    'jest.e2e.config.json',
    'jest.e2e.json',
    'jest-unit.config.js',
    'jest-e2e.config.js',
    'jest-e2e.config.cjs',
    'jest-e2e.config.mjs',
    'jest-e2e.config.ts',
    'jest-e2e.config.cts',
    'jest-e2e.config.mts',
    'jest-e2e.config.json',
    'jest-e2e.json',
    'jest-github-actions-reporter.js',
    'jest.setup.js',
    'jest.setup.ts',
    'jest.json',
    '.jestrc',
    '.jestrc.js',
    '.jestrc.json',
    'jest.teardown.js',
  ],
  histoire: [
    'histoire.config.ts',
    'histoire.config.js',
    '.histoire.js',
    '.histoire.ts',
  ],
  husky: [
    '.huskyrc',
    'husky.config.js',
    '.huskyrc.json',
    '.huskyrc.js',
    '.huskyrc.yaml',
    '.huskyrc.yml',
  ],
  json: [
    '.jscsrc',
    '.jshintrc',
    'composer.lock',
    '.jsbeautifyrc',
    '.esformatter',
    'cdp.pid',
    '.lintstagedrc',
  ],
  laravel: ['artisan'],
  lerna: ['lerna.json'],
  license: [
    'copying',
    'copying.md',
    'copying.rst',
    'copying.txt',
    'copyright',
    'copyright.md',
    'copyright.rst',
    'copyright.txt',
    'license',
    'license-agpl',
    'license-apache',
    'license-bsd',
    'license-mit',
    'license-gpl',
    'license-lgpl',
    'license.md',
    'license.rst',
    'license.txt',
    'licence',
    'licence-agpl',
    'licence-apache',
    'licence-bsd',
    'licence-mit',
    'licence-gpl',
    'licence-lgpl',
    'licence.md',
    'licence.rst',
    'licence.txt',
  ],
  lintstaged: [
    '.lintstagedrc',
    '.lintstagedrc.json',
    '.lintstagedrc.yaml',
    '.lintstagedrc.yml',
    '.lintstagedrc.mjs',
    '.lintstagedrc.cjs',
    '.lintstagedrc.js',
    'lint-staged.config.js',
    'lint-staged.config.mjs',
    'lint-staged.config.cjs',
  ],
  lua: ['.luacheckrc'],
  makefile: ['makefile', 'gnumakefile', 'kbuild'],
  maven: ['maven.config', 'jvm.config', 'pom.xml'],
  netlify: [
    'netlify.json',
    'netlify.yml',
    'netlify.yaml',
    'netlify.toml',
  ],
  next: [
    'next.config.js',
    'next.config.mjs',
    'next.config.ts',
    'next.config.mts',
  ],
  nginx: ['nginx.conf'],
  npm: ['.npmrc'],
  npm_ignore: ['.npmignore'],
  npm_lock: ['package-lock.json'],
  nuxt: ['nuxt.config.js', 'nuxt.config.ts', '.nuxtrc'],
  nuxt_ignore: ['.nuxtignore'],
  package_json: [
    'package.json',
    '.nvmrc',
    '.esmrc',
    '.node-version',
  ],
  playwright: [
    'playwright.config.js',
    'playwright.config.mjs',
    'playwright.config.ts',
    'playwright-ct.config.js',
    'playwright-ct.config.mjs',
    'playwright-ct.config.ts',
  ],
  pnpm: ['pnpm-workspace.yaml', '.pnpmfile.cjs'],
  pnpm_lock: ['pnpm-lock.yaml'],
  prettier: [
    '.prettierrc',
    'prettier.config.js',
    'prettier.config.cjs',
    '.prettierrc.js',
    '.prettierrc.cjs',
    '.prettierrc.json',
    '.prettierrc.json5',
    '.prettierrc.yaml',
    '.prettierrc.yml',
    '.prettierignore',
    '.prettierrc.toml',
  ],
  prettier_ignore: ['.prettierignore'],
  prisma: ['prisma.yml'],
  r: ['.Rhistory'],
  readme: ['readme.md', 'readme.rst', 'readme.txt', 'readme'],
  redwood: ['redwood.toml'],
  renovate: [
    '.renovaterc',
    '.renovaterc.json',
    'renovate-config.json',
    'renovate.json',
    'renovate.json5',
  ],
  robots: ['robots.txt'],
  rollup: [
    'rollup.config.js',
    'rollup.config.mjs',
    'rollup.config.ts',
    'rollup-config.js',
    'rollup-config.mjs',
    'rollup-config.ts',
    'rollup.config.common.js',
    'rollup.config.common.mjs',
    'rollup.config.common.ts',
    'rollup.config.base.js',
    'rollup.config.base.mjs',
    'rollup.config.base.ts',
    'rollup.config.prod.js',
    'rollup.config.prod.mjs',
    'rollup.config.prod.ts',
    'rollup.config.dev.js',
    'rollup.config.dev.mjs',
    'rollup.config.dev.ts',
    'rollup.config.prod.vendor.js',
    'rollup.config.prod.vendor.mjs',
    'rollup.config.prod.vendor.ts',
  ],
  rome: ['rome.json'],
  ruby_gem: ['gemfile'],
  sonar_cloud: [
    'sonar-project.properties',
    '.sonarcloud.properties',
    'sonarcloud.yaml',
  ],
  svelte: [
    'svelte.config.js',
    'svelte.config.cjs',
    'svelte.config.ts',
  ],
  stackblitz: ['.stackblitzrc'],
  stencil: ['stencil.config.js', 'stencil.config.ts'],
  stitches: ['stitches.config.js', 'stitches.config.ts'],
  stylelint: [
    '.stylelintrc',
    'stylelint.config.js',
    'stylelint.config.cjs',
    '.stylelintrc.json',
    '.stylelintrc.yaml',
    '.stylelintrc.yml',
    '.stylelintrc.js',
    '.stylelintrc.cjs',
  ],
  stylelint_ignore: ['.stylelintignore', '.stylelintcache'],
  tailwind: [
    'tailwind.js',
    'tailwind.ts',
    'tailwind.config.js',
    'tailwind.config.cjs',
    'tailwind.config.ts',
    'tailwind.config.cts',
  ],
  tauri: [
    'tauri.conf.json',
    'tauri.config.json',
    'tauri.linux.conf.json',
    'tauri.windows.conf.json',
    'tauri.macos.conf.json',
  ],
  typescript_config: [
    'tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.editor.json',
    'tsconfig.spec.json',
    'tsconfig.base.json',
    'tsconfig.build.json',
    'tsconfig.eslint.json',
    'tsconfig.lib.json',
    'tsconfig.lib.prod.json',
    'tsconfig.node.json',
    'tsconfig.test.json',
    'tsconfig.e2e.json',
    'tsconfig.web.json',
    'tsconfig.webworker.json',
    'tsconfig.worker.json',
    'tsconfig.config.json',
    'tsconfig.vitest.json',
    'tsconfig.cjs.json',
    'tsconfig.esm.json',
    'tsconfig.mjs.json',
    'tsconfig.doc.json',
  ],
  unocss: ['unocss.config.js', 'unocss.config.ts'],
  v: ['vpkg.json', 'v.mod'],
  vercel: ['vercel.json', 'now.json'],
  vercel_ignore: ['.vercelignore', '.nowignore'],
  vite: [
    'vite.config.js',
    'vite.config.mjs',
    'vite.config.cjs',
    'vite.config.ts',
    'vite.config.cts',
    'vite.config.mts',
    'vite.config.js',
    'vite.config.mjs',
    'vite.config.cjs',
    'vite.config.ts',
    'vite.config.cts',
    'vite.config.mts',
  ],
  vitest: [
    'vitest.config.js',
    'vitest.config.mjs',
    'vitest.config.cjs',
    'vitest.config.ts',
    'vitest.config.cts',
    'vitest.config.mts',
    'vitest.config.js',
    'vitest.config.mjs',
    'vitest.config.cjs',
    'vitest.config.ts',
    'vitest.config.cts',
    'vitest.config.mts',
  ],
  vue_config: [
    'vue.config.js',
    'vue.config.ts',
    'vetur.config.js',
    'vetur.config.ts',
    'volar.config.js',
  ],
  webpack: [
    'webpack.js',
    'webpack.cjs',
    'webpack.mjs',
    'webpack.ts',
    'webpack.cts',
    'webpack.mts',
    'webpack.base.js',
    'webpack.base.cjs',
    'webpack.base.mjs',
    'webpack.base.ts',
    'webpack.base.cts',
    'webpack.base.mts',
    'webpack.config.js',
    'webpack.config.cjs',
    'webpack.config.mjs',
    'webpack.config.ts',
    'webpack.config.cts',
    'webpack.config.mts',
    'webpack.common.js',
    'webpack.common.cjs',
    'webpack.common.mjs',
    'webpack.common.ts',
    'webpack.common.cts',
    'webpack.common.mts',
    'webpack.config.common.js',
    'webpack.config.common.cjs',
    'webpack.config.common.mjs',
    'webpack.config.common.ts',
    'webpack.config.common.cts',
    'webpack.config.common.mts',
    'webpack.config.common.babel.js',
    'webpack.config.common.babel.ts',
    'webpack.dev.js',
    'webpack.dev.cjs',
    'webpack.dev.mjs',
    'webpack.dev.ts',
    'webpack.dev.cts',
    'webpack.dev.mts',
    'webpack.development.js',
    'webpack.development.cjs',
    'webpack.development.mjs',
    'webpack.development.ts',
    'webpack.development.cts',
    'webpack.development.mts',
    'webpack.config.dev.js',
    'webpack.config.dev.cjs',
    'webpack.config.dev.mjs',
    'webpack.config.dev.ts',
    'webpack.config.dev.cts',
    'webpack.config.dev.mts',
    'webpack.config.dev.babel.js',
    'webpack.config.dev.babel.ts',
    'webpack.mix.js',
    'webpack.mix.cjs',
    'webpack.mix.mjs',
    'webpack.mix.ts',
    'webpack.mix.cts',
    'webpack.mix.mts',
    'webpack.prod.js',
    'webpack.prod.cjs',
    'webpack.prod.mjs',
    'webpack.prod.ts',
    'webpack.prod.cts',
    'webpack.prod.mts',
    'webpack.prod.config.js',
    'webpack.prod.config.cjs',
    'webpack.prod.config.mjs',
    'webpack.prod.config.ts',
    'webpack.prod.config.cts',
    'webpack.prod.config.mts',
    'webpack.production.js',
    'webpack.production.cjs',
    'webpack.production.mjs',
    'webpack.production.ts',
    'webpack.production.cts',
    'webpack.production.mts',
    'webpack.server.js',
    'webpack.server.cjs',
    'webpack.server.mjs',
    'webpack.server.ts',
    'webpack.server.cts',
    'webpack.server.mts',
    'webpack.client.js',
    'webpack.client.cjs',
    'webpack.client.mjs',
    'webpack.client.ts',
    'webpack.client.cts',
    'webpack.client.mts',
    'webpack.config.server.js',
    'webpack.config.server.cjs',
    'webpack.config.server.mjs',
    'webpack.config.server.ts',
    'webpack.config.server.cts',
    'webpack.config.server.mts',
    'webpack.config.client.js',
    'webpack.config.client.cjs',
    'webpack.config.client.mjs',
    'webpack.config.client.ts',
    'webpack.config.client.cts',
    'webpack.config.client.mts',
    'webpack.config.production.babel.js',
    'webpack.config.production.babel.ts',
    'webpack.config.prod.babel.js',
    'webpack.config.prod.babel.cjs',
    'webpack.config.prod.babel.mjs',
    'webpack.config.prod.babel.ts',
    'webpack.config.prod.babel.cts',
    'webpack.config.prod.babel.mts',
    'webpack.config.prod.js',
    'webpack.config.prod.cjs',
    'webpack.config.prod.mjs',
    'webpack.config.prod.ts',
    'webpack.config.prod.cts',
    'webpack.config.prod.mts',
    'webpack.config.production.js',
    'webpack.config.production.cjs',
    'webpack.config.production.mjs',
    'webpack.config.production.ts',
    'webpack.config.production.cts',
    'webpack.config.production.mts',
    'webpack.config.staging.js',
    'webpack.config.staging.cjs',
    'webpack.config.staging.mjs',
    'webpack.config.staging.ts',
    'webpack.config.staging.cts',
    'webpack.config.staging.mts',
    'webpack.config.babel.js',
    'webpack.config.babel.ts',
    'webpack.config.base.babel.js',
    'webpack.config.base.babel.ts',
    'webpack.config.base.js',
    'webpack.config.base.cjs',
    'webpack.config.base.mjs',
    'webpack.config.base.ts',
    'webpack.config.base.cts',
    'webpack.config.base.mts',
    'webpack.config.staging.babel.js',
    'webpack.config.staging.babel.ts',
    'webpack.config.coffee',
    'webpack.config.test.js',
    'webpack.config.test.cjs',
    'webpack.config.test.mjs',
    'webpack.config.test.ts',
    'webpack.config.test.cts',
    'webpack.config.test.mts',
    'webpack.config.vendor.js',
    'webpack.config.vendor.cjs',
    'webpack.config.vendor.mjs',
    'webpack.config.vendor.ts',
    'webpack.config.vendor.cts',
    'webpack.config.vendor.mts',
    'webpack.config.vendor.production.js',
    'webpack.config.vendor.production.cjs',
    'webpack.config.vendor.production.mjs',
    'webpack.config.vendor.production.ts',
    'webpack.config.vendor.production.cts',
    'webpack.config.vendor.production.mts',
    'webpack.test.js',
    'webpack.test.cjs',
    'webpack.test.mjs',
    'webpack.test.ts',
    'webpack.test.cts',
    'webpack.test.mts',
    'webpack.dist.js',
    'webpack.dist.cjs',
    'webpack.dist.mjs',
    'webpack.dist.ts',
    'webpack.dist.cts',
    'webpack.dist.mts',
    'webpackfile.js',
    'webpackfile.cjs',
    'webpackfile.mjs',
    'webpackfile.ts',
    'webpackfile.cts',
    'webpackfile.mts',
  ],
  windi: [
    'windi.config.js',
    'windi.config.cjs',
    'windi.config.ts',
    'windi.config.cts',
    'windi.config.json',
  ],
  yaml: ['.yamllint', '.yamllint.yml', '.yamllint.yaml'],
  yarn: [
    '.yarnrc',
    '.yarnclean',
    '.yarn-integrity',
    'yarn-error.log',
    '.yarnrc.yml',
    '.yarnrc.yaml',
  ],
  yarn_lock: ['yarn.lock'],
}
