export const languages: IconMap = {
  angular: ['ng-template'],
  api_blueprint: ['apiblueprint'],
  apple: ['applescript'],
  bash: ['awk', 'shellscript'],
  bat: ['bat'],
  binary: ['code-text-binary'],
  c: ['c', 'objective-c', 'objective-cpp'],
  cabal: ['cabal'],
  cadence: ['cadence'],
  clojure: ['clojure'],
  cmake: ['cmake'],
  cmake_in: ['cmake-cache'],
  cobol: ['cobol'],
  coffeescript: ['coffeescript'],
  cpp: ['cpp'],
  csharp: ['csharp'],
  css: ['css'],
  csv: ['csv', 'tsv', 'psv'],
  cucumber: ['cucumber'],
  cuda: ['cuda-cpp'],
  d: ['d'],
  dart: ['dart'],
  database: ['sql'],
  diff: ['diff'],
  django: ['django-html', 'django-txt'],
  docker: ['dockerfile', 'dockercompose'],
  editorconfig: ['editorconfig'],
  elixir: ['elixir'],
  elm: ['elm'],
  env: ['dotenv'],
  erlang: ['erlang'],
  forth: ['forth'],
  fortran: ['fortran'],
  foxpro: ['foxpro'],
  fsharp: ['fsharp'],
  git: ['git', 'git-commit', 'git-rebase', 'ignore'],
  go: ['go'],
  grain: ['grain'],
  graphql: ['graphql'],
  groovy: ['groovy'],
  haml: ['haml'],
  handlebars: ['handlebars'],
  haskell: ['haskell'],
  haxe: ['haxe', 'hxml'],
  hjson: ['hjson'],
  html: ['html'],
  java: ['java'],
  javascript: ['javascript'],
  javascript_react: ['javascriptreact'],
  jinja: ['jinja'],
  json: ['json', 'jsonc', 'json5', 'jsonl'],
  julia: ['julia', 'juliamarkdown'],
  jupyter: ['jupyter'],
  latex: [
    'bibtex',
    'bibtex-style',
    'tex',
    'doctex',
    'latex',
    'latex-expl3',
  ],
  less: ['less'],
  livescript: ['livescript'],
  log: ['log'],
  lua: ['lua'],
  makefile: ['makefile'],
  markdown: ['markdown'],
  nim: ['nim', 'nimble'],
  nix: ['nix'],
  nunjucks: ['nunjucks'],
  pawn: ['pawn'],
  pdf: ['pdf'],
  perl: ['perl', 'perl6'],
  php: ['php'],
  postcss: ['postcss'],
  powershell: ['powershell'],
  processing: ['processing'],
  prolog: ['prolog'],
  properties: ['properties', 'ini', 'spring-boot-properties'],
  pug: ['jade', 'pug'],
  puppet: ['puppet'],
  purescript: ['purescript'],
  python: ['python'],
  r: ['r', 'rsweave'],
  razor: ['razor', 'aspnetcorerazor'],
  reason: ['reason', 'reason_lisp'],
  rescript: ['rescript'],
  riot: ['riot'],
  ruby: ['ruby'],
  rust: ['rust'],
  salesforce: ['apex'],
  sass: ['sass', 'scss'],
  scala: ['scala'],
  scheme: ['scheme'],
  search: ['search-result'],
  shader: ['hlsl', 'glsl', 'wgsl'],
  slim: ['slim'],
  smarty: ['smarty'],
  solidity: ['solidity'],
  spwn: ['spwn'],
  svelte: ['svelte'],
  svg: ['svg'],
  stan: ['stan'],
  swift: ['swift'],
  tailwind: ['tailwindcss'],
  toml: ['toml'],
  twig: ['twig'],
  twine: ['twee3', 'twee3-harlowe-3', 'twee3-chapbook-1', 'twee3-sugarcube-2'],
  txt: ['plaintext'],
  typescript: ['typescript'],
  typescript_react: ['typescriptreact'],
  unity: ['shaderlab'],
  v: ['v'],
  vala: ['vala'],
  visual_studio: ['vb', 'testOutput'],
  vue: [
    'vue',
    'vue-postcss',
    'vue-html',
    'vue-directives',
    'vue-injection-markdown',
    'vue-interpolations',
    'vue-sfc-style-variable-injection',
  ],
  windi: ['windi'],
  wolfram: ['wolframlanguage'],
  xml: ['xml', 'xquery', 'xsl'],
  yaml: [
    'yaml',
    'github-actions-workflow',
    'spring-boot-properties-yaml',
    'ansible',
    'ansible-jinja',
  ],
}
