export const languages: IconMap = {
  angular: ['ng-template'],
  apple: ['applescript'],
  bash: ['awk', 'shellscript'],
  bat: ['bat'],
  binary: ['code-text-binary'],
  c: ['c', 'objective-c', 'objective-cpp'],
  clojure: ['clojure'],
  coffeescript: ['coffeescript'],
  cpp: ['cpp'],
  csharp: ['csharp'],
  css: ['css', 'less', 'postcss'],
  csv: ['csv', 'tsv', 'psv'],
  cucumber: ['cucumber'],
  cuda: ['cuda-cpp'],
  dart: ['dart'],
  database: ['sql'],
  diff: ['diff'],
  django: ['django-html', 'django-txt'],
  docker: ['dockerfile', 'dockercompose'],
  editorconfig: ['editorconfig'],
  elixir: ['elixir'],
  elm: ['elm'],
  env: ['dotenv'],
  erlang: ['erlang'],
  fsharp: ['fsharp'],
  git: ['git', 'git-commit', 'git-rebase', 'ignore'],
  go: ['go'],
  graphql: ['graphql'],
  groovy: ['groovy'],
  handlebars: ['handlebars'],
  haskell: ['haskell'],
  haxe: ['haxe', 'hxml'],
  html: ['html'],
  java: ['java'],
  javascript: ['javascript'],
  javascript_react: ['javascriptreact'],
  jinja: ['jinja'],
  json: ['json', 'jsonc', 'json5', 'jsonl'],
  julia: ['julia', 'juliamarkdown'],
  jupyter: ['jupyter'],
  latex: [
    'bibtex',
    'bibtex-style',
    'tex',
    'doctex',
    'latex',
    'latex-expl3',
  ],
  log: ['log'],
  lua: ['lua'],
  makefile: ['makefile'],
  markdown: ['markdown'],
  nix: ['nix'],
  pdf: ['pdf'],
  perl: ['perl', 'perl6'],
  php: ['php'],
  powershell: ['powershell'],
  processing: ['processing'],
  properties: ['properties', 'ini'],
  purescript: ['purescript'],
  python: ['python'],
  r: ['r', 'rsweave'],
  razor: ['razor', 'aspnetcorerazor'],
  reason: ['reason', 'reason_lisp'],
  rescript: ['rescript'],
  solidity: ['solidity'],
  ruby: ['ruby'],
  rust: ['rust'],
  sass: ['sass', 'scss'],
  scala: ['scala'],
  search: ['search-result'],
  shader: ['hlsl', 'glsl', 'wgsl'],
  svelte: ['svelte'],
  svg: ['svg'],
  swift: ['swift'],
  tailwind: ['tailwindcss'],
  toml: ['toml'],
  twine: ['twee3', 'twee3-harlowe-3', 'twee3-chapbook-1', 'twee3-sugarcube-2'],
  txt: ['plaintext'],
  typescript: ['typescript'],
  typescript_react: ['typescriptreact'],
  unity: ['shaderlab'],
  v: ['v'],
  visual_studio: ['vb', 'testOutput'],
  vue: [
    'vue',
    'vue-postcss',
    'vue-html',
    'vue-directives',
    'vue-injection-markdown',
    'vue-interpolations',
    'vue-sfc-style-variable-injection',
  ],
  windi: ['windi'],
  xml: ['xml', 'xquery', 'xsl'],
  yaml: ['yaml'],
}
