name: Feature request
description: Request a feature for the extension
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: Explain what you want the feature to achieve, including eventual configuration and context.
    validations:
      required: true
