name: Bug report
description: Report a bug or unexpected behaviour
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Explain what issue you ran into, what unexpected behaviour you encoutered. Providing as much context as possible helps.
    validations:
      required: true
