export const extensions: IconMap = {
  angular: ['ng-template'],
  bash: ['bash', 'sh', 'awk'],
  bat: ['bat'],
  c: ['c', 'i', 'mi'],
  clojure: ['clj', 'cljs', 'cljc'],
  coffeescript: ['coffee', 'cson', 'iced'],
  cpp: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
  csharp: ['cs', 'csx'],
  cucumber: ['feature', 'features'],
  cuda: ['cu', 'cuh'],
  dart: ['dart'],
  dart_generated: ['freezed.dart', 'g.dart'],
  database: [
    'pdb',
    'sql',
    'pks',
    'pkb',
    'accdb',
    'mdb',
    'sqlite',
    'sqlite3',
    'pgsql',
    'postgres',
    'psql',
    'db',
    'db3',
  ],
  django: ['djt'],
  docker: ['dockerfile', 'dockerignore'],
  elixir: ['ex', 'exs', 'eex', 'leex', 'heex'],
  elm: ['elm'],
  erlang: ['erl'],
  fsharp: ['fs', 'fsx', 'fsi', 'fsproj'],
  go: ['go'],
  graphql: ['graphql', 'gql'],
  groovy: ['groovy'],
  h: ['h'],
  handlebars: ['hbs', 'mustache'],
  haskell: ['hs'],
  hpp: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
  html: ['htm', 'xhtml', 'html_vm', 'asp'],
  java: ['java', 'jsp'],
  java_class: ['class'],
  java_jar: ['jar'],
  javascript: ['js', 'cjs', 'esx', 'mjs'],
  javascript_map: ['js.map', 'mjs.map', 'cjs.map'],
  json: [
    'json',
    'jsonc',
    'tsbuildinfo',
    'json5',
    'jsonl',
    'ndjson',
  ],
  jsx: ['jsx'],
  julia: ['jl'],
  jupyter: ['ipynb'],
  powershell: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
  python: ['py'],
  python_compiled: ['pyc', 'pyo', 'pyd'],
  svelte: ['svelte'],
  rust: ['rs', 'ron'],
  tsx: ['tsx'],
  typescript: ['ts'],
  typescript_def: ['d.ts', 'd.cts', 'd.mts'],
}
