export const extensions: IconMap = {
  bash: ['bash', 'sh', 'awk'],
  bat: ['bat'],
  c: ['c', 'i', 'mi'],
  cpp: ['cc', 'cpp', 'cxx', 'c++', 'cp', 'mm', 'mii', 'ii'],
  csharp: ['cs', 'csx'],
  h: ['h'],
  hpp: ['hh', 'hpp', 'hxx', 'h++', 'hp', 'tcc', 'inl'],
  powershell: ['ps1', 'psm1', 'psd1', 'ps1xml', 'psc1', 'pssc'],
  python: ['py'],
  python_compiled: ['pyc', 'pyo', 'pyd'],
  svelte: ['svelte'],
  java: ['java', 'jsp'],
  java_class: ['class'],
  java_jar: ['jar'],
  rust: ['rs', 'ron'],
}
