export const files: IconMap = {
  angular: ['angular-cli.json', '.angular-cli.json', 'angular.json'],
  bash: ['commit-msg', 'pre-commit', 'pre-push', 'post-merge'],
  dart: ['.pubignore'],
  docker: ['dockerfile', 'docker-compose.yml', 'docker-compose.yaml'],
  editorconfig: ['.editorconfig'],
  git: [
    '.gitignore',
    '.gitconfig',
    '.gitattributes',
    '.gitmodules',
    '.gitkeep',
    '.git-include',
  ],
  go_mod: ['go.mod', 'go.sum', 'go.work', 'go.work.sum'],
  rollup: [
    'rollup.config.js',
    'rollup.config.mjs',
    'rollup.config.ts',
    'rollup-config.js',
    'rollup-config.mjs',
    'rollup-config.ts',
    'rollup.config.common.js',
    'rollup.config.common.mjs',
    'rollup.config.common.ts',
    'rollup.config.base.js',
    'rollup.config.base.mjs',
    'rollup.config.base.ts',
    'rollup.config.prod.js',
    'rollup.config.prod.mjs',
    'rollup.config.prod.ts',
    'rollup.config.dev.js',
    'rollup.config.dev.mjs',
    'rollup.config.dev.ts',
    'rollup.config.prod.vendor.js',
    'rollup.config.prod.vendor.mjs',
    'rollup.config.prod.vendor.ts',
  ],
  vite: [
    'vite.config.js',
    'vite.config.mjs',
    'vite.config.cjs',
    'vite.config.ts',
    'vite.config.cts',
    'vite.config.mts',
    'vite.config.js',
    'vite.config.mjs',
    'vite.config.cjs',
    'vite.config.ts',
    'vite.config.cts',
    'vite.config.mts',
  ],
  vitest: [
    'vitest.config.js',
    'vitest.config.mjs',
    'vitest.config.cjs',
    'vitest.config.ts',
    'vitest.config.cts',
    'vitest.config.mts',
    'vitest.config.js',
    'vitest.config.mjs',
    'vitest.config.cjs',
    'vitest.config.ts',
    'vitest.config.cts',
    'vitest.config.mts',
  ],
}
