export const languages: IconMap = {
  angular: ['ng-template'],
  bash: ['awk', 'shellscript'],
  bat: ['bat'],
  binary: ['code-text-binary'],
  c: ['c', 'objective-c', 'objective-cpp'],
  clojure: ['clojure'],
  coffeescript: ['coffeescript'],
  cpp: ['cpp'],
  csharp: ['csharp'],
  css: ['css', 'less', 'postcss'],
  cucumber: ['cucumber'],
  cuda: ['cuda-cpp'],
  dart: ['dart'],
  database: ['sql'],
  diff: ['diff'],
  django: ['django-html', 'django-txt'],
  docker: ['dockerfile', 'dockercompose'],
  editorconfig: ['editorconfig'],
  elixir: ['elixir'],
  elm: ['elm'],
  erlang: ['erlang'],
  fsharp: ['fsharp'],
  git: ['git', 'git-commit', 'git-rebase', 'ignore'],
  go: ['go'],
  graphql: ['graphql'],
  groovy: ['groovy'],
  handlebars: ['handlebars'],
  haskell: ['haskell'],
  html: ['html'],
  java: ['java'],
  javascript: ['javascript'],
  json: ['json', 'jsonc', 'json5'],
  jsx: ['javascriptreact'],
  julia: ['julia', 'juliamarkdown'],
  jupyter: ['jupyter'],
  log: ['log'],
  lua: ['lua'],
  makefile: ['makefile'],
  markdown: ['markdown'],
  pdf: ['pdf'],
  perl: ['perl'],
  php: ['php'],
  powershell: ['powershell'],
  properties: ['properties'],
  python: ['python'],
  r: ['r', 'rsweave'],
  razor: ['razor', 'aspnetcorerazor'],
  reason: ['reason', 'reason_lisp'],
  rescript: ['rescript'],
  ruby: ['ruby'],
  svelte: ['svelte'],
  typescript: ['typescript'],
  tsx: ['typescriptreact'],
  vue: [
    'vue',
    'vue-postcss',
    'vue-html',
    'vue-directives',
    'vue-injection-markdown',
    'vue-interpolations',
    'vue-sfc-style-variable-injection',
  ],
}
