export const languages: IconMap = {
  angular: ['ng-template'],
  bash: ['awk', 'shellscript'],
  bat: ['bat'],
  binary: ['code-text-binary'],
  c: ['c', 'objective-c', 'objective-cpp'],
  clojure: ['clojure'],
  cpp: ['cpp'],
  csharp: ['csharp'],
  editorconfig: ['editorconfig'],
  java: ['java'],
  powershell: ['powershell'],
  python: ['python'],
  svelte: ['svelte'],
  vue: [
    'vue',
    'vue-postcss',
    'vue-html',
    'vue-directives',
    'vue-injection-markdown',
    'vue-interpolations',
    'vue-sfc-style-variable-injection',
  ],
}
