name: Generate Previews

on:
  push:
    branches: [main]
    tags-ignore: [v*]

jobs:
  generate-previews:
    name: Generate Previews
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate Flavor Previews
        run: pnpm icons:preview

      - name: Generate Catwalk Preview
        run: pnpm catwalk

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: re-generate previews'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: chore/re-generate-previews
          delete-branch: true
          title: 'chore: re-generate previews'
