name: Generate Previews

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'icons/**'
      - scripts/icons/preview.ts
      - scripts/catwalk.ts
    tags-ignore: [v*]

jobs:
  generate-previews:
    name: Generate Previews
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate Flavor Previews
        run: pnpm icons:preview

      - name: Setup catppuccin/catwalk
        uses: catppuccin/setup-catwalk@v1.0.0

      - name: Generate Catwalk Preview
        run: pnpm catwalk

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore: re-generate previews'
          commit-message: 'chore: re-generate previews'
          branch: chore/re-generate-previews
          delete-branch: true
          add-paths: |
            assets/*
