name: Generate Previews

on:
  workflow_dispatch:

jobs:
  generate-previews:
    name: Generate Previews
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate Flavor Previews
        run: pnpm icons:preview

      - name: Setup catppuccin/catwalk
        uses: catppuccin/setup-catwalk@v1.0.0

      - name: Generate Catwalk Preview
        run: pnpm catwalk

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          file_pattern: 'assets/*'
          commit_message: 'chore: regenerate previews'
